<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * B_Item_CompleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class B_Item_CompleteRepository extends EntityRepository
{
}
