<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * B_QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class B_QuestionRepository extends EntityRepository
{
}
