<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * B_Section_ReadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class B_Section_ReadingRepository extends EntityRepository
{
}
