<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Inciso_Multiple_SelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Inciso_Multiple_SelectionRepository extends EntityRepository
{
}
