<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Item_True_FalseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Item_True_FalseRepository extends EntityRepository
{
}
