<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Item_List_SelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Item_List_SelectionRepository extends EntityRepository
{
}
