<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Respuesta_CompletaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Respuesta_CompletaRepository extends EntityRepository
{
}
