<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Respuesta_Multiple_SelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Respuesta_Multiple_SelectionRepository extends EntityRepository
{
}
