<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Section_ListeningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Section_ListeningRepository extends EntityRepository
{
}
