<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Section_ReadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Section_ReadingRepository extends EntityRepository
{
}
