<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Valor_Lista_SeleccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Valor_Lista_SeleccionRepository extends EntityRepository
{
}
